package racingcar.utils

const val MIN_CAR_NAME_LENGTH = 1
const val MAX_CAR_NAME_LENGTH = 5

const val MIN_ROUND_COUNT = 1
const val MAX_ROUND_COUNT = Int.MAX_VALUE

const val RANDOM_SEED = 10

const val START_RANDOM_MOVEMENT_PROBABILITY = 1
const val END_RANDOM_MOVEMENT_PROBABILITY = 10
const val MOVEMENT_PROBABILITY = 4